export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";
export const COUNT_ACTION_STARTED = "COUNT_ACTION_STARTED";
export const COUNT_ACTION_FINISHED = "COUNT_ACTION_FINISHED";